#!/bin/python3
# -*- coding: UTF-8 -*-

# 读取changelog文件


def read_changelog():
    changelog = open("CHANGELOG.md", "r")
    changelog_list = changelog.readlines()
    changelog.close()
    return changelog_list


changelog_list = read_changelog()

first = True

# 打印changelog_list中最新版本号的所有内容

for line in changelog_list:
    if line.startswith("## ") or line.startswith("# "):
        if first:
            print(line, end="")
            first = False
            continue
        else:
            break
    else:
        if not first:
            print(line, end="")
