#!/bin/python3
# -*- coding: UTF-8 -*-
import sys

# 读取changelog文件


def read_changelog():
    changelog = open("CHANGELOG.md", "r")
    changelog_list = changelog.readlines()
    changelog.close()
    return changelog_list


changelog_list = read_changelog()


version = str(sys.argv[1])

first = True

# 打印changelog_list中最新版本号的所有内容，第一行不打印

for line in changelog_list:
    if line.startswith("## ") or line.startswith("# "):
        if (version in line) and first:
            first = False
            continue
        else:
            break
    else:
        print(line, end="")
