#!/bin/python3
# -*- coding: UTF-8 -*-

# run npm version

import os
import sys

args=sys.argv

os.system("cd ./app && npm version " + " ".join(args[1:]))
os.system('git add ./app/package.json')
os.system('git commit -m "chore: update app version"')
os.system("npm version " + " ".join(args[1:]))
