name: Deploy Extension
on:
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.13.0]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: pnpm run publish $VSCE_TOKEN
      - name: get version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: get body
        id: body
        run: python scripts/read-changelog ${{steps.version.outputs.value}}
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.version.outputs.value}}
          body: ${{steps.body.outputs.value}}
          token: ${{ secrets.RELEASE_TOKEN }}
          draft: false
          prerelease: false
          files: |
            *.vsix
            LICENSE
