name: Deploy Extension
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.17.1]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: pnpm run publish $VSCE_TOKEN
      # ---------- to change this
      - name: get version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
      # ----------
      - name: get description
        id: description
        uses: juliangruber/read-file-action@v1
        with:
          path: ./docs/description.md
      - name: package
        run: pnpm run package
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.version.outputs.value}}
          body: ${{steps.description.outputs.content}}
          token: ${{ secrets.RELEASE_TOKEN }}
          draft: false
          prerelease: false
          files: |
            noveler-${{steps.version.outputs.value}}.vsix
            LICENSE
